services:
  app:
    container_name: crud
    build: .
    environment:
      SECRET_DB_HOST: db
      SECRET_DB_PORT: 3306
      SECRET_DB_NAME: crud
      SECRET_DB_USER: root
      SECRET_DB_PASS: 1234
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crud
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-server
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: unless-stopped