services:
  app:
    container_name: crud
    build: .
    env_file:
      - .env
    environment:
      SECRET_DB_HOST: db
      SECRET_DB_PORT: ${DB_PORT}
      SECRET_DB_NAME: ${MYSQL_DATABASE}
      SECRET_DB_USER: ${MYSQL_USER}
      SECRET_DB_PASS: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: mysql
    container_name: mysqldb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-server
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "${PMA_PORT:-8081}:80"
    depends_on:
      - db
    restart: unless-stopped